### ISSUE TITLE
Add `getVersion` method to get Matador version

### ISSUE THREAD

**Issue by saliougaye** [nullndr/Matador#10]
Add a `getVersion` method that takes VERSION enviroment variable of Matador

**Comment by nullndr** [comment]
@saliougaye what is the `VERSION` env variable?

**Comment by nullndr** [comment]
@saliougaye I don't think the name `getVersion` is the right name for this, because it say nothing about what the version is about.

I would prefer `getMatadorVersion`, do you agree?

**Comment by saliougaye** [comment]
It's okay for me. I only need the version to set it on the UI
